SVG icons for landing page
eclipse-esmf/eclipse-esmf.github.io pull request #43
Opened 2024-03-18 13:00 UTC by aniluede

Now the landing page uses SVGs instead of PNG for the icons, thus improving image resolution when displayed on larger screens while reducing load time

2024-03-26 08:00 UTC, michelu89 commented on documentation/modules/ROOT/pages/index.adoc
> +image::ESMF-SAMM-icon-vector.svg[xref=samm-specification:ROOT:index.adoc, window=_blank,opts=nofollow]
Where are the .svg's stored?

2024-03-26 13:50 UTC, atextor requested changes

2024-03-26 13:50 UTC, atextor commented on documentation/modules/ROOT/pages/index.adoc
> +image::ESMF-AspectModel-icon-vector.svg[xref=ame-guide:ROOT:introduction.adoc, window=_blank,opts=nofollow]
The referenced SVG files are not included in the PR.

2024-04-05 09:34 UTC, aniluede commented
Sorry, not sure how this happened but here are the missing SVGs. Local build worked well and looked well. @michelu89 @atextor

2024-04-24 06:00 UTC, atextor approved these changes

2024-04-24 06:00 UTC, merged